### ISSUE TITLE
Remove "Advanced Features" password field

### ISSUE THREAD

**Issue by samiebee43** [WasatchPhotonics/EnlightenMobile#25]

**Comment by mzieg** [comment]
In such cases, please inquire why the feature was added in the first place and what requirement is being met.  Authentication is never added casually.

**Comment by mzieg** [comment]
I looked at this...agreed, nothing is being shielded here that we haven't since exposed on ENLIGHTEN's "Expert" tab anyway. Sorry for the knee-jerk reaction, I get twitchy around laser safety :-)

(Please do add ENLIGHTEN's warning about disabling the laser watchdog.)

**Comment by samiebee43** [comment]
This removal included everything behind the password field too. The field wasn't working and it also had keyboard issues, so I'm taking out until I can properly replace it.
